services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq-container
    container_name: 'rabbit'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
